# Generated by Django 5.2.12 on 2026-04-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('src', models.CharField()),
            ],
        ),
    ]
