# Generated by Django 5.2.12 on 2026-04-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
